### ISSUE TITLE
在mac os13上不起作用

### ISSUE THREAD

**Issue by zzb16888** [hoochanlon/Free-NTFS-for-Mac#1]
在mac os13上不起作用

**Comment by hoochanlon** [comment]
* 截图过来看下，你有没有关闭SIP？
* 把软件放在应用程序目录打开？
* 密码是你电脑开机密码

**Comment by hoochanlon** [comment]
已完善readme说明，新增“注意事项”模块。

**Comment by hoochanlon** [comment]
<img width="885" alt="截屏2023-01-15 00 04 24" src="https://user-images.githubusercontent.com/35732922/212481971-6baeb5c8-8ada-429f-a76c-49d3ea3e54e4.png">
