### ISSUE TITLE
未获得授权将Apple事件发送给Terminal。 (-1743)

### ISSUE THREAD

**Issue by chechekk** [hoochanlon/Free-NTFS-for-Mac#16]
请问这个错误是什么原因造成的？我记得之前可以用的。

**Comment by hoochanlon** [comment]
见：

* https://stackoverflow.com/questions/51299066/macos-mojave-automator-not-authorized-to-send-apple-events-to-system-events
* [Apple Developer Forums - Mojave beta 6 breaks Applescripts](https://developer.apple.com/forums/thread/106949)

如下：

![catch2023-05-06 10 00 57](https://user-images.githubusercontent.com/35732922/236592723-0b7e6bb6-d489-47b8-b727-c069bada8114.png)

![catch2023-05-06 10 11 56](https://user-images.githubusercontent.com/35732922/236593155-068391a9-5a54-43d7-ba7c-8d66109da7bc.png)

**Comment by chechekk** [comment]
<img width="715" alt="iShot_2023-05-06_10 17 25" src="https://user-images.githubusercontent.com/4943291/236593520-2e69d980-8b00-43f4-869e-1d505e316f31.png">
我的自动化不知道为什么是这样，有可能是老版Mac强制装的新系统导致的吗？
