### ISSUE TITLE
启动安全性实用工具

### ISSUE THREAD

**Issue by linxuanzhao** [hoochanlon/Free-NTFS-for-Mac#17]
这个老电脑是不是没有办法？我15年pro，启动安全性实用工具，没有后面两个选项，只能设置固件密码。
我看苹果文档说是要 Apple T2 安全芯片的 Mac启动安全性实用工具，才有后面两个选项

**Comment by hoochanlon** [comment]
https://github.com/hoochanlon/Free-NTFS-for-Mac/issues/1#issue-1510757015
