### ISSUE TITLE
提示部分文件找不到，最后显示可读写，但是系统中看不到挂载的盘

### ISSUE THREAD

**Issue by wenkeming** [hoochanlon/Free-NTFS-for-Mac#19]
<img width="570" alt="image" src="https://github.com/hoochanlon/Free-NTFS-for-Mac/assets/8252267/2297c66f-65db-4663-9b8d-9dbc4f326e39">

**Comment by wenkeming** [comment]
<img width="406" alt="image" src="https://github.com/hoochanlon/Free-NTFS-for-Mac/assets/8252267/ff8d2c3c-05b1-4e0b-818e-d778f43bab10">
已安装macfuse

**Comment by hoochanlon** [comment]
检查是否安装好了 ntfs-3g
```
which ntfs-3g
```
