### ISSUE TITLE
macos14 不能正常使用 似乎是脚本参数解析有误

### ISSUE THREAD

**Issue by ltlly** [hoochanlon/Free-NTFS-for-Mac#20]
系统版本 版本14.0 Beta版(23A5328b)

调试打印 once twice  thriceCutVal三个变量依次为 /dev  /dev  disk4s1
疑似解析参数有误
而mount | grep ntfs返回
/dev/disk4s1 on /Volumes/D (ntfs, local, nodev, nosuid, read-only, noowners, noatime)

目前个人自用脚本 将脚本修改为
```shell
line=$(mount | grep ntfs)

# 提取disk和volume名称
disk=$(echo "$line" | awk '{split($1, a, "/"); print a[3]}')
volume=$(echo "$line" | awk '{split($3, a, "/"); print a[3]}')
echo "Disk: $disk"
echo "Volume: $volume"
sudo umount /dev/$disk
sudo -S  ntfs-3g /dev/$disk  /Volumes/$volume -olocal -oallow_other -o auto_xattr -ovolname=$volume

```
即解析后运行
sudo umount  /dev/disk4s1
sudo -S  ntfs-3g /dev/disk4s1  /Volumes/D -olocal -oallow_other -o auto_xattr -ovolname=D  
可以正常使用

**Comment by hoochanlon** [comment]
macOS14相关报错

```
News, support and information:  https://github.com/tuxera/ntfs-3g/
新设备: disk4s1，已可读写！
---------
 
新设备: disk4s1
ntfs-3g: Failed to access volume '/dev//dev': No such file or directory

ntfs-3g 2022.10.3 external FUSE 29 - Third Generation NTFS Driver
		Configuration type 1, XATTRS are on, POSIX ACLS are off

```

**Comment by hoochanlon** [comment]
* [x] Other

![catch2023-11-23 22 37 48](https://github.com/hoochanlon/Free-NTFS-for-Mac/assets/35732922/80105506-9926-45ee-8a49-dc255188da5b)

**Comment by hoochanlon** [comment]
1.3版本及以上版本由终端升级到electron图形化界面，详请见发布说明：
 
* https://github.com/hoochanlon/Free-NTFS-for-Mac/releases/tag/v1.3

<img width="2204" height="1764" alt="Image" src="https://github.com/user-attachments/assets/46fefa4d-4c2e-4c65-b9c8-6d8f97050d80" />
