### ISSUE TITLE
启用后盘符不见了

### ISSUE THREAD

**Issue by L1ech0** [hoochanlon/Free-NTFS-for-Mac#22]

**Comment by L1L1L1C** [comment]
<img width="557" alt="image" src="https://github.com/hoochanlon/Free-NTFS-for-Mac/assets/110832755/5af343a4-414b-4dff-a5f6-4cf20437cb7a">

**Comment by olive009** [comment]
同样的问题

**Comment by bikingfree1989** [comment]
同样的问题，抓紧解决。

**Comment by hoochanlon** [comment]
brew tap gromgit/homebrew-fuse && brew install --cask macfuse && brew install ntfs-3g-mac

**Comment by hoochanlon** [comment]
See for yourself：https://developer.apple.com/forums/thread/712310
