### ISSUE TITLE
MacOS 14 上 报错： sudo: /dev/disk4s1: command not found

### ISSUE THREAD

**Issue by qinzhenlove** [hoochanlon/Free-NTFS-for-Mac#23]
MacOS 14 使用时会出现下面的情况
![51697106914_ pic](https://github.com/hoochanlon/Free-NTFS-for-Mac/assets/44219596/b2674fd3-6e2f-465c-b728-0d0ffa91a0b3)

然后硬盘就被卸载了，重新挂载上硬盘又会反复出现上面的情况，还是没法写入。

**Comment by hoochanlon** [comment]
#22
