### ISSUE TITLE
“该磁盘没有挂载“

### ISSUE THREAD

**Issue by XinyeWu007** [hoochanlon/Free-NTFS-for-Mac#24]
您好，我的电脑是：Apple M1 Pro, Ventura 13.6，nigate以方法二（命令行下载到本地）安装成功后，读取磁盘时出现了“该磁盘没有挂载的提示，无法写入。”请问要怎么解决呢？

另外，我在没有执行nigate时，是可以正常用NTFStool查看硬盘的。

**Comment by hoochanlon** [comment]
自己去插下再拔下，复制报错，百度或者在已有的issue找下解决办法。 https://github.com/hoochanlon/Free-NTFS-for-Mac/issues/9

**Comment by XinyeWu007** [comment]
是开启了nigate才这样，重新装载也会自动断开
















在 2023-11-07 17:26:53，"123456" ***@***.***> 写道：

自己去插下再拔下，复制报错，百度或者在已有的issue找下解决办法。 #9
